baseURL = 'https://davidburke.me/'
languageCode = 'en-us'
theme = 'Stack'
defaultContentLanguage = 'en'

[outputs]
    home = ["HTML", "RSS", "JSON"]

[pagination]
    pagerSize = 5

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"
