[en]
languageName = "English"
title = "David Burke"
weight = 1

[en.params.sidebar]
subtitle = "A place for my thoughts on all sorts of topics, including digital accessibility, human-computer interaction (HCI), self-hosting, hardware projects and Linux stuff."
